---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
